### PR TITLE
use code tag instead of .code css class

### PR DESCRIPTION
**Pull request by MartinNowak**
- better html semantic and fixes
  compat with some css frameworks

### CODE REVIEW

**Comment by MartinNowak** [comment]
Any chance to merge this as well and tag a new ddox release? FWIW it's the last issue for scod.

**Comment by s-ludwig** [comment]
I had a quick look through some code using Ddox to see if any formatting would be broken, but it looks like all of them are already handling `<pre><code>` correctly. I'll merge and have a look at #89 before creating a new tag.

**Comment by MartinNowak** [comment]
> them are already handling `<pre><code>` correctly.

Yes, prettify.css handles both `pre.code` and `pre: code`.

BTW, I used phantomjs to scan the whole sitemap.xml for those tags, might come in handy somewhere else.

```bash
ddox serve-html --sitemap-url 'http://127.0.0.1:8080/'
curl localhost:8080/sitemap.xml | sed -n 's|.*<loc>\(.*\)</loc>.*|\1|p' | xargs phantomjs test.js
```
```js
var page = require('webpage').create(), system = require('system');

function check(urls) {
    if (!urls.length)
        phantom.exit();
    var url = urls.shift();
    page.open(url, function(status) {
        var elems = page.evaluate(function() {
            return document.querySelectorAll('code code');
        });
        if (elems.length)
            console.log(url);
        check(urls);
    });
}

check(system.args.slice(1));
```

**Comment by MartinNowak** [comment]
> Yes, prettify.css handles both pre.code and pre: code.

Should have checked this more thoroughly.
I was a bit confused b/c skeleton styles the code element instead of the pre element.

**Pull request merged**
