### PR TITLE
Implement a static search results page.

### PR DESCRIPTION
**Pull request by s-ludwig**
image

### CODE REVIEW

**Comment by s-ludwig** [comment]
Rebased and applied some filter/sorting fixes, so it yields the same list as the find-as-you-type search:
image

**Comment by adamdruppe** [comment]
Hah nice. Amusingly, yesterday, I implemented a javascript search for adrdox after doing a cgi style one first. I generally prefer the server-side generated thing, but the javascript one was requested for compatibility with github pages.

**Comment by s-ludwig** [comment]
For ddox, I think, it was the other was around because dlang.org is just organized as a bunch of HTML files, so static generation was the priority. But apart from that I also prefer a server-side solution, and of course downloading the whole symbol file ~800KB eagerly isn't really nice either (~70KB gzipped).

**Comment by adamdruppe** [comment]
Aye, I had the same problem. And the server side one can cache the indexes much better giving quite a nice speedup. Regardless, this will be good!

**Comment by s-ludwig** [comment]
True, I didn't tackle indexes yet, because they really only get interesting on a more global scale (like on dpldocs.info). For a few thousand symbols, the search time isn't really noticeable yet. My next priority will have to be memory use, which is quite high right now with the uncompressed AST stored fully in memory.

**Pull request merged**
