### PR TITLE
Static syntax highlighting - issue #93

### PR DESCRIPTION
**Pull request by s-ludwig**
Has the drawback of putting more load on the server and network, but that shouldn't be too bad.

### CODE REVIEW

**Comment by Abscissa** [comment]
>Has the drawback of putting more load on the server and network, but that shouldn't be too bad.

I can't imagine it would if it's built with ```ddox generate-html``` and served as static files. If anything, it's just be a negligible difference in filesize. Does ```ddox serve-html``` re-generate the docs on each request?

**Comment by s-ludwig** [comment]
>> Has the drawback of putting more load on the server and network, but that shouldn't be too bad.

> I can't imagine it would if it's built with ddox generate-html and served as static files. If anything, it's just be a negligible difference in filesize. Does ddox serve-html re-generate the docs on each request?

There are a *lot* of additional `<span class="xyz"></span>` strings in the output, so about 26 bytes per keyword, string, number, identifier etc. For medium sized examples that can easily be a few KBs. Nothing bad, but on a high-load service this can definitely make a difference. `ddox serve-html` indeed regenerates the pages for each request, which generally should be very fast. It just currently does far more dynamic memory allocations than necessary.

All in all, I'm definitely in favor of this change, but I'll defer this slightly until it has been tested a little more.

**Comment by MartinNowak** [comment]
Good idea to get rid of prettify-js.

**Comment by MartinNowak** [comment]
libdparse is at 0.4.0 in the meantime, so might make sense to update before adapting much of the code

**Comment by s-ludwig** [comment]
Updated to libdparse 0.4.0 and rebased+squashed.

**Comment by s-ludwig** [comment]
Hm, strange: https://ddox-test-uploads.herokuapp.com/uploads/104846930
Where does that grid come from...

**Comment by s-ludwig** [comment]
Nice, one issue already caught! Just the grid is still there: https://ddox-test-uploads.herokuapp.com/uploads/104848883

**Comment by s-ludwig** [comment]
Okay, seems to have been just a diagnostic tool. Looks good now.

**Comment by MartinNowak** [comment]
Let's do it.

**Comment by MartinNowak** [comment]
Can we tag a new release for this?

**Comment by s-ludwig** [comment]
v0.13.0 is now listed.

**Pull request merged**
