### PR TITLE
Fix conflicting overloads in test/issue180_return/test.d

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
They are illegal and cause a deprecation with dlang/dmd#8429

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Ping

**Comment by MoonlightSentinel** [comment]
Could you tag a new release for BuildKite?

**Comment by wilzbach** [comment]
Yeah, I have already done so -https://github.com/rejectedsoftware/ddox/releases/tag/v0.16.16

**Comment by MoonlightSentinel** [comment]
Thanks

**Pull request merged**
