### PR TITLE
add visual tests for ddox rendering

### PR DESCRIPTION
**Pull request by MartinNowak**
- using phantomcss for diff comparison

### CODE REVIEW

**Comment by MartinNowak** [comment]
There is a small heroku app running for the uploads.
https://ddox-test-uploads.herokuapp.com/

**Comment by s-ludwig** [comment]
Interesting! That would also be especially interesting in conjunction with custom style tests, so that unintended CSS "APi" changes get caught. How is the process for updating the reference images for intended visual changes - downloading the images off the heroku app?

**Comment by MartinNowak** [comment]
> downloading the images off the heroku app?

Yes you can do that, in fact due to sub-pixel differences on different platforms, the ones produced locally might not match.
A better place to upload pictures would make sense though, heroku fs is ephemeral (1 hour until suspend).

**Comment by MartinNowak** [comment]
Just made a dummy style change to show the diffing.

**Comment by s-ludwig** [comment]
Okay, I guess I could store those on my server, it would just need some kind of basic security mechanisms. Is it maybe possible to upload a private key to Travis for doing client-authentication?

**Comment by s-ludwig** [comment]
> Just made a dummy style change to show the diffing.

Looks good. Of course it would be possible to go crazy with some JavaScript to enhance the UI, but I think this is already useful enough.

**Comment by s-ludwig** [comment]
WRT private keys, this sounds like it could be useful: https://docs.travis-ci.com/user/encryption-keys/

**Comment by MartinNowak** [comment]
> Is it maybe possible to upload a private key to Travis for doing client-authentication?

Yes you can store them as secure variable, but those aren't available to PRs.

**Comment by s-ludwig** [comment]
So do PRs have a different pair of keys? Otherwise I'd just encrypt a username/password key and use HTTPS+basic auth for the upload.

**Comment by MartinNowak** [comment]
> Yes you can store them as secure variable, but those aren't available to PRs.

A pastbin for images would be nice.

**Comment by s-ludwig** [comment]
Nevermind w.r.t. the secure variables, I'm reading up on it now.

**Comment by s-ludwig** [comment]
Okay, I'll merge it like this for now. Will be interesting to see what the syntax highlighting PR does. Sad that Travis doesn't just offer an ssh-agent with a fixed generated key, so that scp could be used.

**Pull request merged**
